# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFileiphonex():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fileiphonex(self):
    self.driver.get("https://www.lazada.vn/#?")
    self.driver.set_window_size(786, 808)
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "q").send_keys("i phone x")
    self.driver.find_element(By.LINK_TEXT, "SEARCH").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(2) .RfADt").click()
    assert self.driver.find_element(By.LINK_TEXT, "[E-Voucher] Sở hữu lPhone 15 Pro Max 512Gb - Basic 2024").text == "[E-Voucher] Sở hữu lPhone 15 Pro Max 512Gb - Basic 2024"
    self.driver.execute_script("window.scrollTo(0,772.7999877929688)")
    self.driver.execute_script("window.scrollTo(0,992.7999877929688)")
    self.driver.execute_script("window.scrollTo(0,1238.4000244140625)")
    self.driver.execute_script("window.scrollTo(0,1543.199951171875)")
    self.driver.execute_script("window.scrollTo(0,1546.4000244140625)")
    self.driver.execute_script("window.scrollTo(0,1690.4000244140625)")
    self.driver.execute_script("window.scrollTo(0,1911.199951171875)")
    self.driver.execute_script("window.scrollTo(0,922.4000244140625)")
    self.driver.execute_script("window.scrollTo(0,540.7999877929688)")
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(6) .buTCk").click()
    self.driver.find_element(By.LINK_TEXT, "SEARCH").click()
  
